import { config } from "dotenv";
config();

export const {
  PORT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_NAME,
  DB_MAX_CONNECTIONS_POOL,
  DB_MIN_CONNECTIONS_POOL,
  DB_ACCQUIRE_TIME,
  DB_IDLE_TIME,
  JWT_SECRET,
  SMTP_EMAIL,
  SMTP_PORT,
  SMTP_HOST,
  SMTP_PASSWORD,
  EMAIL_FROM,
  FRONTEND_URL,
  COOKIE_DOMAIN,
  COOKIE_PATH_TALENT,
  COOKIE_SAME_SITE,
  COOKIE_SECURE,
  CSRF_CHECK,
  LOG_LEVEL,
} = process.env;
